### ISSUE TITLE
ODMax fails at step 3

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#15]
project_task_open=11
project_task_expanded=370cb660-4e2b-48c4-a4de-99c94979fa10

@OKaluza, this Project is shared with you.
Fails at step 3

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In [3], line 27
     25 res = odm_requests.post_task(url, token, project_id, data=data)
     26 task = res.json()
---> 27 task_id = res.json()["id"]
     28 print(task)

KeyError: 'id'

**Comment by OKaluza** [comment]
To document what we found, setting dtm=False or dsm=False in the task options causes a 400 "invalid options" response. This was because the ODMax code to convert a python dict to the json array expected by WebODM had an error and needed to encode true/false in lowercase as JSON expects. It's now fixed: https://github.com/AuScalableDroneCloud/pipelines-jupyter/commit/921af2a355503e3446b54311301dbc0ef6bd9640

**Comment by TimeScience** [comment]
Thanks!
________________________________
