### ISSUE TITLE
Camera images still missing from ODM tasks

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#22]
This seems to continue to be an issue. See for example:
https://asdc.cloud.edu.au/public/task/c4786612-d9f4-4085-9be0-b0e41ab27b15/3d/

**Comment by OKaluza** [comment]
This is caused by OpenDroneMap putting an underscore in the filename of some of the images, for the images that don't show you will see the filename has been changed, eg:
https://asdc.cloud.edu.au/api/projects/460/tasks/c4786612-d9f4-4085-9be0-b0e41ab27b15/images/thumbnail/GSAM4469_.JPG?size=320
If you remove the underscore it works fine
https://asdc.cloud.edu.au/api/projects/460/tasks/c4786612-d9f4-4085-9be0-b0e41ab27b15/images/thumbnail/GSAM4469.JPG?size=320

If you look at the images list, it seems random which have this underscore and which don't https://asdc.cloud.edu.au/api/projects/460/tasks/c4786612-d9f4-4085-9be0-b0e41ab27b15/assets/images.json
All the actual image files exist on the volume without the underscore.

I have no idea why it does this, we'll probably have to raise an issue in https://github.com/OpenDroneMap/ODM

**Comment by OKaluza** [comment]
Actually, this appears to be the same issue as the images being doubled up after duplicating a task - the duplicate images have an underscore appended

**Comment by OKaluza** [comment]
I've fixed this as it was caused by the same duplicate image bug, which is now solved. If you see it happen again please re-open and link an example, but the missing shots in above task are definitely because of the duplicate bug.
