### ISSUE TITLE
All jupyter notebooks fail at import tasks step - need to extend timeout?

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/Tracker#28]
Hi,

Every notebook fails at the step where it reads the task list. Can we please ASAP extend the timeout to see if this fixes the issue? I can't currently test any jupyter code.
If extending the timeout hangs things for a while then we might want to add a note to the user so they know to wait or something similar.

![image](https://user-images.githubusercontent.com/3067588/218721383-bcfaf13a-9b85-4f48-a3c8-c45a7e5f1115.png)

**Comment by OKaluza** [comment]
I've been working on a fix for this which I finished this morning, the design of WebODM has a problem where the potentially huge console_output field is stored as a column in the app_task table, the table the bulk of the queries look up, this creates a huge unnecessary burden on the database engine when this data is only rarely viewed or needed.

I've wrote a script to clear the console output field and store it as a text file for backup, the output is already stored as a text file in assets/task_output.txt but I wanted to be sure so saved it anyway.

I tested this extensively on dev and demonstrated clear speedups to all queries (~50% reduction in time), even with the small number of projects and tasks in this site.

I've now run the script on production and the difference is huge:
# Before
```
$ curl https://asdc.cloud.edu.au/api/plugins/asdc/usertasks?email=tim.brown@anu.edu.au -o /tmp/out.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36790  100 36790    0     0   1513      0  0:00:24  0:00:24 --:--:--  9090
```
~ 24 seconds to query all your tasks
# After
```
$ time curl https://asdc.cloud.edu.au/api/plugins/asdc/usertasks?email=tim.brown@anu.edu.au -o /tmp/out.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36790  100 36790    0     0  46204      0 --:--:-- --:--:-- --:--:-- 46160

real    0m0.809s
```
Less than 1 second

Please try it out in jupyter, but based on these test queries I think you'll have no more problems with timeouts.

I'll have to amend WebODM to ensure all future tasks have their console output cleared on completion instead of leaving this in the database and fix the output viewer to load the data from the stored text file when the column has been cleared.

**Comment by TimeScience** [comment]
It works!
That seems to have fixed it.

Thanks!
